"""soft_leads — add name column

Revision ID: 030c01ae2f05
Revises: 887ca5894acd
Create Date: 2026-04-04 22:30:15.363778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030c01ae2f05'
down_revision: Union[str, Sequence[str], None] = '887ca5894acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soft_leads', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soft_leads', 'name')
    # ### end Alembic commands ###
