"""initial schema — 12 tables

Revision ID: 8bcbc66b3897
Revises: 
Create Date: 2026-04-03 16:49:16.754024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcbc66b3897'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeded_areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('business_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supabase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_supabase_uid'), 'user_profiles', ['supabase_uid'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tone_of_voice', sa.String(), nullable=True),
    sa.Column('brand_keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_user_id'), 'organizations', ['user_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sslcommerz_transaction_id', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('outlets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('outlet_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('google_place_id', sa.String(), nullable=True),
    sa.Column('maps_url', sa.String(), nullable=True),
    sa.Column('facebook_page_url', sa.String(), nullable=True),
    sa.Column('instagram_handle', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('next_audit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outlets_organization_id'), 'outlets', ['organization_id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('outlet_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('google_place_id', sa.String(), nullable=True),
    sa.Column('maps_url', sa.String(), nullable=True),
    sa.Column('facebook_page_url', sa.String(), nullable=True),
    sa.Column('instagram_handle', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('cached_data', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gap_analysis', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_outlet_id'), 'competitors', ['outlet_id'], unique=False)
    op.create_table('weekly_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('outlet_id', sa.Uuid(), nullable=True),
    sa.Column('google_place_id', sa.String(), nullable=True),
    sa.Column('is_free_audit', sa.Boolean(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_phase', sa.String(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('score_delta', sa.Integer(), nullable=True),
    sa.Column('phase_progress', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_audits_google_place_id'), 'weekly_audits', ['google_place_id'], unique=False)
    op.create_index(op.f('ix_weekly_audits_outlet_id'), 'weekly_audits', ['outlet_id'], unique=False)
    op.create_table('audit_dimensions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['weekly_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_dimensions_audit_id'), 'audit_dimensions', ['audit_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('outlet_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['weekly_audits.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_audit_id'), 'missions', ['audit_id'], unique=False)
    op.create_index(op.f('ix_missions_outlet_id'), 'missions', ['outlet_id'], unique=False)
    op.create_table('soft_leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=False),
    sa.Column('google_place_id', sa.String(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['weekly_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soft_leads_google_place_id'), 'soft_leads', ['google_place_id'], unique=False)
    op.create_table('content_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('copy_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_drafts_mission_id'), 'content_drafts', ['mission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_drafts_mission_id'), table_name='content_drafts')
    op.drop_table('content_drafts')
    op.drop_index(op.f('ix_soft_leads_google_place_id'), table_name='soft_leads')
    op.drop_table('soft_leads')
    op.drop_index(op.f('ix_missions_outlet_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_audit_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_audit_dimensions_audit_id'), table_name='audit_dimensions')
    op.drop_table('audit_dimensions')
    op.drop_index(op.f('ix_weekly_audits_outlet_id'), table_name='weekly_audits')
    op.drop_index(op.f('ix_weekly_audits_google_place_id'), table_name='weekly_audits')
    op.drop_table('weekly_audits')
    op.drop_index(op.f('ix_competitors_outlet_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_outlets_organization_id'), table_name='outlets')
    op.drop_table('outlets')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_organizations_user_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_user_profiles_supabase_uid'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('seeded_areas')
    # ### end Alembic commands ###
