"""competitors — nullable outlet_id, add seeded_area_id and website_url

Revision ID: bbd857b9748f
Revises: 8bcbc66b3897
Create Date: 2026-04-03 16:56:51.569346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd857b9748f'
down_revision: Union[str, Sequence[str], None] = '8bcbc66b3897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('seeded_area_id', sa.Uuid(), nullable=True))
    op.add_column('competitors', sa.Column('website_url', sa.String(), nullable=True))
    op.alter_column('competitors', 'outlet_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_competitors_seeded_area_id'), 'competitors', ['seeded_area_id'], unique=False)
    op.create_foreign_key(None, 'competitors', 'seeded_areas', ['seeded_area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competitors', type_='foreignkey')
    op.drop_index(op.f('ix_competitors_seeded_area_id'), table_name='competitors')
    op.alter_column('competitors', 'outlet_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('competitors', 'website_url')
    op.drop_column('competitors', 'seeded_area_id')
    # ### end Alembic commands ###
