"""add discover_users and user_reviews tables

Revision ID: bff2561d41d1
Revises: 030c01ae2f05
Create Date: 2026-04-06 18:05:12.119112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff2561d41d1'
down_revision: Union[str, Sequence[str], None] = '030c01ae2f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discover_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discover_users_phone'), 'discover_users', ['phone'], unique=True)
    op.create_table('user_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('food_good', sa.Boolean(), nullable=False),
    sa.Column('environment_good', sa.Boolean(), nullable=False),
    sa.Column('would_recommend', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['discover_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_reviews_business_id'), 'user_reviews', ['business_id'], unique=False)
    op.create_index(op.f('ix_user_reviews_user_id'), 'user_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reviews_user_id'), table_name='user_reviews')
    op.drop_index(op.f('ix_user_reviews_business_id'), table_name='user_reviews')
    op.drop_table('user_reviews')
    op.drop_index(op.f('ix_discover_users_phone'), table_name='discover_users')
    op.drop_table('discover_users')
    # ### end Alembic commands ###
