"""competitors — add postcode, lat, lng columns

Revision ID: ed10d7bbf693
Revises: bbd857b9748f
Create Date: 2026-04-03 22:20:53.708311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed10d7bbf693'
down_revision: Union[str, Sequence[str], None] = 'bbd857b9748f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('postcode', sa.String(), nullable=True))
    op.add_column('competitors', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('competitors', sa.Column('lng', sa.Float(), nullable=True))
    op.create_index(op.f('ix_competitors_postcode'), 'competitors', ['postcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitors_postcode'), table_name='competitors')
    op.drop_column('competitors', 'lng')
    op.drop_column('competitors', 'lat')
    op.drop_column('competitors', 'postcode')
    # ### end Alembic commands ###
